### ISSUE TITLE
Storage options cannot be specified for s3

### ISSUE THREAD

**Issue by garethbridger** [jjneely/whisper-backup#23]
Attempting to specify storage options for s3 results in the following error:

```
/usr/local/bin/whisper-backup -b mybucket backup s3 region=eu-west-1
Traceback (most recent call last):
  File "/usr/local/bin/whisper-backup", line 11, in <module>
    load_entry_point('whisper-backup==0.3.0', 'console_scripts', 'whisper-backup')()
  File "/usr/local/lib/python2.7/dist-packages/whisper_backup-0.3.0-py2.7.egg/whisperbackup/whisperbackup.py", line 526, in main
    script.store = storageBackend(script)
  File "/usr/local/lib/python2.7/dist-packages/whisper_backup-0.3.0-py2.7.egg/whisperbackup/whisperbackup.py", line 86, in storageBackend
    gcsargs[fields[0]] = fields[1]
UnboundLocalError: local variable 'gcsargs' referenced before assignment
```

This looks to be caused by a minor copypasta

**Comment by garethbridger** [comment]
Opened pull request: https://github.com/jjneely/whisper-backup/pull/24

**Comment by jjneely** [comment]
Awesome!  Thank you!  Merged.
